### ISSUE TITLE
Improve repository

### ISSUE THREAD

**Issue by RMCampos** [ricardo-campos-org/react-typescript-todolist#26]
## TODO

- [x] Fix README with better names and descriptions
- [x] Add Issues template
- [x] Add PR template

**Comment by RMCampos** [comment]
Ended up improving a bit more:

- [ ] Added logo (with ChatGPT)
- [ ] Added favicon
- [ ] Removed CRA and added Vite
- [ ] Added ESLint (Airbnb)
- [ ] Added Vitest and basic coverage plugins
- [ ] Added license

**Comment by RMCampos** [comment]
Good to go!
![image](https://github.com/user-attachments/assets/5833d776-ea7c-4c94-8a19-b4035c2ffae6)
